apiVersion: v1
kind: Service
metadata:
  name: poco-sell-dev
  namespace: poco
  labels:
    app: poco-sell-dev
spec:
  type: NodePort
  ports:
  - name: poco-sell-dev
    port: 3000
    targetPort: poco-sell-dev
  selector:
    app: poco-sell-dev
